# Generated by Django 3.1.6 on 2021-02-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_content_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentfile',
            name='category',
        ),
        migrations.AddField(
            model_name='contentfile',
            name='category',
            field=models.ManyToManyField(null=True, to='main.Content'),
        ),
    ]
